<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\{CurrentLocation,LocationHistory,LocationSyncBatch,PrivacyAcknowledgement,WorkSession}; use App\Services\TenantClock; use App\Support\ApiResponse; use Carbon\CarbonImmutable; use Illuminate\Http\Request; use Illuminate\Support\Facades\Cache; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
class GpsController extends Controller {
 public function ingest(Request $r,TenantClock $clock){$r->validate(['batch_uuid'=>'required|uuid','locations'=>'required|array|min:1|max:'.config('tenancy.tracking.max_batch_points',100)]);$u=$r->user()->load(['tenant','salesman']);$device=$r->attributes->get('device');$batchUuid=$r->string('batch_uuid')->toString();$submitted=$r->input('locations',[]);$batch=LocationSyncBatch::firstOrCreate(['tenant_id'=>$u->tenant_id,'device_id'=>$device->id,'user_id'=>$u->id,'batch_uuid'=>$batchUuid],['point_count'=>count($submitted),'received_at'=>now()]);$accepted=[];$duplicates=[];$rejected=[];$details=[];
  foreach($submitted as $i=>$p){$uuid=$p['client_uuid']??null;$reject=function($code)use(&$rejected,&$details,$i,$uuid){if($uuid)$rejected[]=$uuid;$details[]=['index'=>$i,'client_uuid'=>$uuid,'code'=>$code,'reason'=>$code];}; if(!$uuid||!Str::isUuid($uuid)){ $reject('malformed_uuid'); continue;} if(LocationHistory::where('tenant_id',$u->tenant_id)->where('client_uuid',$uuid)->exists()){ $duplicates[]=$uuid; continue;} $lat=$p['latitude']??null;$lng=$p['longitude']??null;$acc=$p['accuracy']??null;$speed=$p['speed']??0;$recorded=$p['recorded_at']??null; if(!is_numeric($lat)||!is_numeric($lng)||$lat<-90||$lat>90||$lng<-180||$lng>180||((float)$lat===0.0&&(float)$lng===0.0)){ $reject('invalid_coordinates'); continue;} if(!is_numeric($acc)||(float)$acc<0||(float)$acc>200){$reject('low_accuracy');continue;}if(is_numeric($speed)&&(float)$speed>55){$reject('invalid_speed');continue;}try{$at=CarbonImmutable::parse($recorded)->utc();}catch(\Throwable){$reject('invalid_timestamp');continue;}if($at->gt(now()->addMinutes(5))){$reject('future_timestamp');continue;} $localDate=$clock->localDate($u->tenant,$at); $session=WorkSession::where('tenant_id',$u->tenant_id)->where('user_id',$u->id)->where(function($q)use($localDate,$at){$q->whereDate('date',$localDate)->orWhere(function($q2)use($at){$q2->where('status','active')->where('start_time','<=',$at);});})->latest('start_time')->first(); if(!$session){$reject('no_work_session');continue;}
   DB::transaction(function()use($u,$device,$batch,$p,$uuid,$lat,$lng,$acc,$at,&$accepted){$row=LocationHistory::create(['tenant_id'=>$u->tenant_id,'user_id'=>$u->id,'salesman_id'=>$u->salesman->id,'device_id'=>$device->id,'client_uuid'=>$uuid,'latitude'=>$lat,'longitude'=>$lng,'horizontal_accuracy'=>$acc,'altitude'=>$p['altitude']??null,'speed'=>$p['speed']??null,'heading'=>$p['heading']??null,'battery_level'=>$p['battery_level']??null,'is_charging'=>(bool)($p['is_charging']??false),'network_status'=>$p['network_status']??null,'is_mock_location'=>(bool)($p['is_mock_location']??false),'provider'=>$p['provider']??null,'recorded_at'=>$at,'received_at'=>now(),'sync_batch_id'=>$batch->id,'sequence_number'=>$p['sequence_number']??null,'metadata'=>null]); $current=CurrentLocation::where('tenant_id',$u->tenant_id)->where('user_id',$u->id)->lockForUpdate()->first(); if(!$current||$at->gt($current->recorded_at)){CurrentLocation::updateOrCreate(['tenant_id'=>$u->tenant_id,'user_id'=>$u->id],['salesman_id'=>$u->salesman->id,'device_id'=>$device->id,'location_history_id'=>$row->id,'latitude'=>$lat,'longitude'=>$lng,'horizontal_accuracy'=>$acc,'altitude'=>$p['altitude']??null,'speed'=>$p['speed']??null,'heading'=>$p['heading']??null,'battery_level'=>$p['battery_level']??null,'is_charging'=>(bool)($p['is_charging']??false),'network_status'=>$p['network_status']??null,'is_mock_location'=>(bool)($p['is_mock_location']??false),'provider'=>$p['provider']??null,'recorded_at'=>$at,'received_at'=>now()]);} $accepted[]=$uuid;});
  }
  $batch->update(['processed_at'=>now()]); DB::afterCommit(function()use($u){try{$cur=CurrentLocation::where('tenant_id',$u->tenant_id)->where('user_id',$u->id)->first();if($cur)Cache::store('redis')->put('latest-location:'.$u->tenant_id.':'.$u->id,$cur->toArray(),3600);}catch(\Throwable){}}); return ApiResponse::success(['accepted'=>count($accepted),'rejected'=>count($rejected),'duplicates'=>count($duplicates),'batch_id'=>$batch->id,'accepted_uuids'=>$accepted,'duplicate_uuids'=>$duplicates,'rejected_uuids'=>$rejected,'rejected_details'=>$details],201);
 }
 public function current(Request $r){$u=$r->user();$c=CurrentLocation::where('tenant_id',$u->tenant_id)->where('user_id',$u->id)->first();return ApiResponse::success($c);}
 public function history(Request $r,TenantClock $clock){$u=$r->user()->load('tenant');$date=$r->validate(['date'=>'required|date_format:Y-m-d'])['date'];$tz=$clock->timezone($u->tenant);$start=CarbonImmutable::parse($date.' 00:00:00',$tz)->utc();$end=$start->addDay();$rows=LocationHistory::where('tenant_id',$u->tenant_id)->where('user_id',$u->id)->where('recorded_at','>=',$start)->where('recorded_at','<',$end)->orderBy('recorded_at')->get();$distance=0.0;for($i=1;$i<$rows->count();$i++){$distance+=$this->distance($rows[$i-1]->latitude,$rows[$i-1]->longitude,$rows[$i]->latitude,$rows[$i]->longitude);}return ApiResponse::success(['locations'=>$rows,'summary'=>['total_points'=>$rows->count(),'distance_km'=>round($distance,3),'first_point'=>$rows->first(),'last_point'=>$rows->last()]]);}
 public function acknowledge(Request $r){$v=$r->validate(['policy_version'=>'required|string|max:50','acknowledged_at'=>'required|date','app_version'=>'required|string|max:50']);$u=$r->user();$d=$r->attributes->get('device');$ack=PrivacyAcknowledgement::firstOrCreate(['tenant_id'=>$u->tenant_id,'user_id'=>$u->id,'device_id'=>$d->id,'policy_version'=>$v['policy_version']],['uuid'=>(string)Str::uuid(),'acknowledged_at'=>$v['acknowledged_at'],'app_version'=>$v['app_version'],'recorded_at'=>now()]);return ApiResponse::success(['id'=>$ack->id,'uuid'=>$ack->uuid,'policy_version'=>$ack->policy_version,'acknowledged_at'=>$ack->acknowledged_at?->toISOString(),'recorded_at'=>$ack->recorded_at?->toISOString()],$ack->wasRecentlyCreated?201:200);}
 private function distance($lat1,$lon1,$lat2,$lon2):float{$r=6371;$dLat=deg2rad($lat2-$lat1);$dLon=deg2rad($lon2-$lon1);$a=sin($dLat/2)**2+cos(deg2rad($lat1))*cos(deg2rad($lat2))*sin($dLon/2)**2;return $r*2*atan2(sqrt($a),sqrt(1-$a));}
}
