<x-layouts.app>
<div class="mb-6 flex flex-wrap items-start justify-between gap-4">
    <div>
        <h1 class="text-2xl font-bold">{{ __('AI insights') }}</h1>
        <p class="mt-1 text-sm text-slate-400">{{ __('Grounded recommendations and manager Q&A from FieldPulse operational data.') }}</p>
    </div>
    <span class="rounded-full px-3 py-1 text-xs font-semibold {{ $providerEnabled ? 'bg-emerald-500/10 text-emerald-300' : 'bg-slate-800 text-slate-300' }}">
        {{ $providerEnabled ? __('AI provider connected') : __('Grounded local mode') }}
    </span>
</div>

<section class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    <div class="rounded-2xl border border-white/10 bg-slate-900 p-5">
        <p class="text-xs uppercase tracking-wide text-slate-400">{{ __('Visits today') }}</p>
        <p class="mt-2 text-3xl font-bold">{{ $snapshot['visits_today'] }}</p>
    </div>
    <div class="rounded-2xl border border-white/10 bg-slate-900 p-5">
        <p class="text-xs uppercase tracking-wide text-slate-400">{{ __('Overdue follow-ups') }}</p>
        <p class="mt-2 text-3xl font-bold {{ $snapshot['overdue_followups'] > 0 ? 'text-rose-300' : '' }}">{{ $snapshot['overdue_followups'] }}</p>
    </div>
    <div class="rounded-2xl border border-white/10 bg-slate-900 p-5">
        <p class="text-xs uppercase tracking-wide text-slate-400">{{ __('Customers not visited in 30 days') }}</p>
        <p class="mt-2 text-3xl font-bold {{ $snapshot['customers_not_visited_30_days'] > 0 ? 'text-amber-300' : '' }}">{{ $snapshot['customers_not_visited_30_days'] }}</p>
    </div>
    <div class="rounded-2xl border border-white/10 bg-slate-900 p-5">
        <p class="text-xs uppercase tracking-wide text-slate-400">{{ __('Salesmen started today') }}</p>
        <p class="mt-2 text-3xl font-bold">{{ $snapshot['salesmen_started_today'] }} / {{ $snapshot['active_salesmen'] }}</p>
    </div>
</section>

<div class="grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
    <section class="rounded-2xl border border-white/10 bg-slate-900 p-5">
        <div class="mb-4">
            <h2 class="text-lg font-semibold">{{ __('Recommended actions') }}</h2>
            <p class="mt-1 text-sm text-slate-400">{{ __('Generated from overdue work, visit coverage, approvals and attendance exceptions.') }}</p>
        </div>
        <div class="space-y-3">
            @foreach($snapshot['recommendations'] as $recommendation)
                @php
                    $tone = match($recommendation['severity']) {
                        'high' => 'border-rose-400/20 bg-rose-500/10',
                        'medium' => 'border-amber-400/20 bg-amber-500/10',
                        default => 'border-emerald-400/20 bg-emerald-500/10',
                    };
                @endphp
                <article class="rounded-xl border p-4 {{ $tone }}">
                    <div class="flex items-start justify-between gap-4">
                        <div>
                            <h3 class="font-semibold">{{ __($recommendation['title']) }}</h3>
                            <p class="mt-1 text-sm text-slate-200">{{ __($recommendation['message'], $recommendation['message_params'] ?? []) }}</p>
                            <p class="mt-2 text-sm text-slate-400">{{ __($recommendation['action']) }}</p>
                        </div>
                        <span class="rounded-full bg-black/20 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide">{{ __($recommendation['severity']) }}</span>
                    </div>
                </article>
            @endforeach
        </div>
    </section>

    <section class="rounded-2xl border border-white/10 bg-slate-900 p-5">
        <h2 class="text-lg font-semibold">{{ __('Ask FieldPulse') }}</h2>
        <p class="mt-1 text-sm text-slate-400">{{ __('Ask about sales, collections, visits, follow-ups or field attendance.') }}</p>

        <form method="POST" action="{{ route('admin.ai-insights.ask') }}" class="mt-4 space-y-3">
            @csrf
            <textarea name="question" rows="4" maxlength="500" required class="w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" placeholder="{{ __('Example: How is customer coverage looking today?') }}">{{ old('question', $question) }}</textarea>
            <button class="w-full rounded-xl bg-indigo-500 px-4 py-3 font-semibold">{{ __('Ask FieldPulse') }}</button>
        </form>

        @if($answer)
            <div class="mt-5 rounded-xl border border-indigo-400/20 bg-indigo-500/10 p-4">
                <p class="text-xs font-semibold uppercase tracking-wide text-indigo-300">{{ __('Answer') }}</p>
                <p class="mt-2 whitespace-pre-line text-sm leading-6">{{ $answer }}</p>
                <p class="mt-3 text-xs text-slate-500">
                    {{ $answerSource === 'configured_ai_provider' ? __('Generated by the configured AI provider from aggregate FieldPulse metrics.') : __('Generated locally from FieldPulse metrics without an external AI provider.') }}
                </p>
            </div>
        @endif

        <div class="mt-5 border-t border-white/10 pt-4 text-xs text-slate-500">
            {{ __('External AI, when enabled, receives aggregate metrics only. Customer names and raw transaction records are not sent by this feature.') }}
        </div>
    </section>
</div>

<section class="mt-6 rounded-2xl border border-white/10 bg-slate-900 p-5">
    <h2 class="text-lg font-semibold">{{ __('7-day commercial pulse') }}</h2>
    <div class="mt-4 grid gap-4 md:grid-cols-2">
        <div class="rounded-xl bg-slate-950 p-4">
            <p class="text-sm text-slate-400">{{ __('Approved sales') }}</p>
            <div class="mt-2 flex flex-wrap gap-2">
                @forelse($snapshot['approved_sales_7d'] as $currency => $amount)
                    <span class="rounded-lg bg-white/5 px-3 py-2 font-semibold">{{ $currency }} {{ number_format($amount, 2) }}</span>
                @empty
                    <span class="text-sm text-slate-500">{{ __('No approved sales recorded.') }}</span>
                @endforelse
            </div>
        </div>
        <div class="rounded-xl bg-slate-950 p-4">
            <p class="text-sm text-slate-400">{{ __('Verified collections') }}</p>
            <div class="mt-2 flex flex-wrap gap-2">
                @forelse($snapshot['verified_collections_7d'] as $currency => $amount)
                    <span class="rounded-lg bg-white/5 px-3 py-2 font-semibold">{{ $currency }} {{ number_format($amount, 2) }}</span>
                @empty
                    <span class="text-sm text-slate-500">{{ __('No verified collections recorded.') }}</span>
                @endforelse
            </div>
        </div>
    </div>
</section>
</x-layouts.app>
