@php($selectedDays = collect(old('weekdays', $route->weekdays ?? [])))
<div class="grid gap-5 md:grid-cols-2">
    <label class="block"><span class="text-sm text-slate-300">Code</span><input name="code" value="{{ old('code', $route->code ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="block"><span class="text-sm text-slate-300">Name</span><input name="name" value="{{ old('name', $route->name ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="block"><span class="text-sm text-slate-300">Branch</span><select name="branch_id" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">Unassigned</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string) old('branch_id', $route->branch_id ?? '') === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm text-slate-300">Territory</span><select name="territory_id" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">Unassigned</option>@foreach($territories as $territory)<option value="{{ $territory->id }}" @selected((string) old('territory_id', $route->territory_id ?? '') === (string) $territory->id)>{{ $territory->code }} — {{ $territory->name }}</option>@endforeach</select></label>
    <fieldset class="md:col-span-2"><legend class="text-sm text-slate-300">Recurring weekdays</legend><div class="mt-2 flex flex-wrap gap-3">@foreach(['mon'=>'Mon','tue'=>'Tue','wed'=>'Wed','thu'=>'Thu','fri'=>'Fri','sat'=>'Sat','sun'=>'Sun'] as $value=>$label)<label class="rounded-lg bg-slate-950 px-3 py-2"><input type="checkbox" name="weekdays[]" value="{{ $value }}" @checked($selectedDays->contains($value))> {{ $label }}</label>@endforeach</div></fieldset>
    <label class="block md:col-span-2"><span class="text-sm text-slate-300">Description</span><textarea name="description" rows="3" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3">{{ old('description', $route->description ?? '') }}</textarea></label>
    <label class="flex items-center gap-3 md:col-span-2"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $route->is_active ?? true))><span>Active route</span></label>
</div>
