<?php
namespace Tests\Feature;
use App\Models\{Device,Salesman,Tenant,User,WorkSession}; use App\Tenancy\TenantContext; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Str; use Laravel\Sanctum\Sanctum; use Tests\TestCase;
class FieldSalesApiTest extends TestCase { use RefreshDatabase; private function actor():array{$t=Tenant::create(['uuid'=>(string)Str::uuid(),'name'=>'T','slug'=>'t','timezone'=>'Asia/Kabul']);$context=app(TenantContext::class);[$u,$s,$d]=$context->withPlatformScope(function()use($t){$u=User::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$t->id,'name'=>'S','email'=>'s@x.test','password'=>Hash::make('password'),'role'=>'salesman','is_active'=>true]);$s=Salesman::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$t->id,'user_id'=>$u->id,'employee_code'=>'1','first_name'=>'S','is_active'=>true]);$d=Device::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$t->id,'user_id'=>$u->id,'salesman_id'=>$s->id,'device_uuid'=>'device-1','installation_uuid'=>'install-1','is_active'=>true]);return[$u,$s,$d];});Sanctum::actingAs($u);return compact('t','u','s','d');} private function headers(){return ['X-Device-UUID'=>'device-1','X-Installation-UUID'=>'install-1','X-App-Version'=>'1.0','X-Platform'=>'android'];}
 public function test_start_is_idempotent_and_preserves_offline_start_time():void{$a=$this->actor();$uuid=(string)Str::uuid();$body=['latitude'=>34.55,'longitude'=>69.2,'accuracy'=>10,'offline_uuid'=>$uuid,'started_at'=>'2026-09-18T04:30:00Z'];$this->postJson('/api/v1/attendance/start',$body,$this->headers())->assertCreated()->assertJsonPath('data.offline_uuid',$uuid)->assertJsonPath('data.started_at','2026-09-18T04:30:00.000000Z');$this->postJson('/api/v1/attendance/start',$body,$this->headers())->assertOk();$this->assertDatabaseCount('work_sessions',1);}
 public function test_second_session_same_local_day_conflicts():void{$this->actor();$this->postJson('/api/v1/attendance/start',['latitude'=>34.5,'longitude'=>69.1,'accuracy'=>5,'offline_uuid'=>(string)Str::uuid(),'started_at'=>'2026-09-18T05:00:00Z'],$this->headers())->assertCreated();$this->postJson('/api/v1/attendance/start',['latitude'=>34.5,'longitude'=>69.1,'accuracy'=>5,'offline_uuid'=>(string)Str::uuid(),'started_at'=>'2026-09-18T06:00:00Z'],$this->headers())->assertStatus(409)->assertJsonPath('error.code','SESSION_ALREADY_EXISTS');}
 public function test_revoked_device_has_machine_code():void{$a=$this->actor();$a['d']->update(['revoked_at'=>now(),'is_active'=>false]);$this->postJson('/api/v1/attendance/start',['latitude'=>34.5,'longitude'=>69.1,'accuracy'=>5,'offline_uuid'=>(string)Str::uuid()],$this->headers())->assertStatus(403)->assertJsonPath('error.code','DEVICE_REVOKED');}
 public function test_mixed_gps_batch_maps_each_verdict():void{$a=$this->actor();WorkSession::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$a['t']->id,'user_id'=>$a['u']->id,'salesman_id'=>$a['s']->id,'device_id'=>$a['d']->id,'date'=>'2026-09-18','start_time'=>'2026-09-18 00:00:00','start_latitude'=>34.5,'start_longitude'=>69.1,'start_accuracy'=>5,'status'=>'active']);$u1=(string)Str::uuid();$u2=(string)Str::uuid();$payload=['batch_uuid'=>(string)Str::uuid(),'locations'=>[['client_uuid'=>$u1,'latitude'=>34.55,'longitude'=>69.2,'accuracy'=>8,'recorded_at'=>'2026-09-18T05:00:00Z','sequence_number'=>1],['client_uuid'=>$u2,'latitude'=>34.55,'longitude'=>69.2,'accuracy'=>999,'recorded_at'=>'2026-09-18T05:01:00Z','sequence_number'=>2]]];$this->postJson('/api/v1/gps/locations',$payload,$this->headers())->assertCreated()->assertJsonPath('data.accepted',1)->assertJsonPath('data.rejected',1)->assertJsonPath('data.duplicates',0);$payload['batch_uuid']=(string)Str::uuid();$payload['locations']=[$payload['locations'][0]];$this->postJson('/api/v1/gps/locations',$payload,$this->headers())->assertJsonPath('data.duplicates',1);}
 public function test_out_of_order_point_does_not_regress_current_location():void{$a=$this->actor();WorkSession::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$a['t']->id,'user_id'=>$a['u']->id,'salesman_id'=>$a['s']->id,'device_id'=>$a['d']->id,'date'=>'2026-09-18','start_time'=>'2026-09-18 00:00:00','start_latitude'=>34.5,'start_longitude'=>69.1,'start_accuracy'=>5,'status'=>'active']);foreach([['2026-09-18T05:10:00Z',34.60],['2026-09-18T05:00:00Z',34.50]] as [$time,$lat])$this->postJson('/api/v1/gps/locations',['batch_uuid'=>(string)Str::uuid(),'locations'=>[['client_uuid'=>(string)Str::uuid(),'latitude'=>$lat,'longitude'=>69.2,'accuracy'=>8,'recorded_at'=>$time,'sequence_number'=>1]]],$this->headers())->assertCreated();$this->assertDatabaseHas('current_locations',['latitude'=>34.6000000]);}
 public function test_active_overnight_session_accepts_post_midnight_point():void{$a=$this->actor();$a['t']->update(['timezone'=>'Asia/Kabul']);WorkSession::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$a['t']->id,'user_id'=>$a['u']->id,'salesman_id'=>$a['s']->id,'device_id'=>$a['d']->id,'date'=>'2026-09-18','start_time'=>'2026-09-18 16:00:00','start_latitude'=>34.5,'start_longitude'=>69.1,'start_accuracy'=>5,'status'=>'active']);$this->postJson('/api/v1/gps/locations',['batch_uuid'=>(string)Str::uuid(),'locations'=>[['client_uuid'=>(string)Str::uuid(),'latitude'=>34.5,'longitude'=>69.1,'accuracy'=>8,'recorded_at'=>'2026-09-18T20:00:00Z','sequence_number'=>1]]],$this->headers())->assertJsonPath('data.accepted',1);}
 public function test_privacy_ack_is_idempotent():void{$this->actor();$body=['policy_version'=>'1','acknowledged_at'=>'2026-09-18T05:00:00Z','app_version'=>'1.0.0'];$this->postJson('/api/v1/gps/privacy-acknowledgement',$body,$this->headers())->assertCreated();$this->postJson('/api/v1/gps/privacy-acknowledgement',$body,$this->headers())->assertOk();$this->assertDatabaseCount('privacy_acknowledgements',1);}
 public function test_settings_defaults_are_safe():void{$this->actor();$this->getJson('/api/v1/settings/attendance-tracking')->assertOk()->assertJsonPath('data.work_session_start_mode','manual')->assertJsonPath('data.gps_tracking_enabled',true)->assertJsonPath('data.timezone','Asia/Kabul');}
}
