<div class="grid gap-5 md:grid-cols-2">
    <label class="block"><span class="text-sm text-slate-300">Code</span><input name="code" value="{{ old('code', $customer->code ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="block"><span class="text-sm text-slate-300">Name</span><input name="name" value="{{ old('name', $customer->name ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="block"><span class="text-sm text-slate-300">Branch</span><select name="branch_id" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">Unassigned</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string) old('branch_id', $customer->branch_id ?? '') === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm text-slate-300">Territory</span><select name="territory_id" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">Unassigned</option>@foreach($territories as $territory)<option value="{{ $territory->id }}" @selected((string) old('territory_id', $customer->territory_id ?? '') === (string) $territory->id)>{{ $territory->code }} — {{ $territory->name }}</option>@endforeach</select></label>
    <label class="block md:col-span-2"><span class="text-sm text-slate-300">Price list</span><select name="price_list_id" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">Use product base prices</option>@foreach($priceLists as $priceList)<option value="{{ $priceList->id }}" @selected((string) old('price_list_id', $customer->price_list_id ?? '') === (string) $priceList->id)>{{ $priceList->code }} — {{ $priceList->name }} ({{ $priceList->currency }})</option>@endforeach</select></label>
    <label class="block"><span class="text-sm text-slate-300">Contact person</span><input name="contact_person" value="{{ old('contact_person', $customer->contact_person ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">Phone</span><input name="phone" value="{{ old('phone', $customer->phone ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">Alternate phone</span><input name="alternate_phone" value="{{ old('alternate_phone', $customer->alternate_phone ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">Email</span><input type="email" name="email" value="{{ old('email', $customer->email ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block md:col-span-2"><span class="text-sm text-slate-300">Address</span><textarea name="address" rows="2" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3">{{ old('address', $customer->address ?? '') }}</textarea></label>
    <label class="block"><span class="text-sm text-slate-300">Latitude</span><input name="latitude" value="{{ old('latitude', $customer->latitude ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">Longitude</span><input name="longitude" value="{{ old('longitude', $customer->longitude ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">Geofence radius (m)</span><input type="number" min="25" max="1000" name="geofence_radius_meters" value="{{ old('geofence_radius_meters', $customer->geofence_radius_meters ?? 100) }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="flex items-center gap-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $customer->is_active ?? true))><span>Active customer</span></label>
</div>
