<div class="grid gap-5 md:grid-cols-2">
    <label class="block"><span class="text-sm text-slate-300">{{ __('Code') }}</span><input name="code" value="{{ old('code', $customer->code ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Name') }}</span><input name="name" value="{{ old('name', $customer->name ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Branch') }}</span><select name="branch_id" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">{{ __('Unassigned') }}</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string) old('branch_id', $customer->branch_id ?? '') === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Territory') }}</span><select name="territory_id" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">{{ __('Unassigned') }}</option>@foreach($territories as $territory)<option value="{{ $territory->id }}" @selected((string) old('territory_id', $customer->territory_id ?? '') === (string) $territory->id)>{{ $territory->code }} — {{ $territory->name }}</option>@endforeach</select></label>
    <label class="block md:col-span-2"><span class="text-sm text-slate-300">{{ __('Price list') }}</span><select name="price_list_id" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">{{ __('Use product base prices') }}</option>@foreach($priceLists as $priceList)<option value="{{ $priceList->id }}" @selected((string) old('price_list_id', $customer->price_list_id ?? '') === (string) $priceList->id)>{{ $priceList->code }} — {{ $priceList->name }} ({{ $priceList->currency }})</option>@endforeach</select></label>
    <div class="md:col-span-2 border-t border-white/10 pt-5"><h3 class="font-semibold">{{ __('Credit settings') }}</h3><p class="mt-1 text-xs text-slate-400">{{ __('Leave the credit limit blank for no enforced limit. A zero limit requires manager override for every credit approval.') }}</p></div>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Credit limit') }}</span><input type="number" min="0" step="0.01" name="credit_limit" value="{{ old('credit_limit', $customer->credit_limit ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Credit currency') }}</span><select name="credit_currency" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3">@foreach(['AFN','USD','PKR'] as $currency)<option value="{{ $currency }}" @selected(old('credit_currency', $customer->credit_currency ?? 'AFN') === $currency)>{{ $currency }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Credit terms (days)') }}</span><input type="number" min="0" max="365" name="credit_terms_days" value="{{ old('credit_terms_days', $customer->credit_terms_days ?? 30) }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Contact person') }}</span><input name="contact_person" value="{{ old('contact_person', $customer->contact_person ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Phone') }}</span><input name="phone" value="{{ old('phone', $customer->phone ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Alternate phone') }}</span><input name="alternate_phone" value="{{ old('alternate_phone', $customer->alternate_phone ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Email') }}</span><input type="email" name="email" value="{{ old('email', $customer->email ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block md:col-span-2"><span class="text-sm text-slate-300">{{ __('Address') }}</span><textarea name="address" rows="2" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3">{{ old('address', $customer->address ?? '') }}</textarea></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Latitude') }}</span><input name="latitude" value="{{ old('latitude', $customer->latitude ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Longitude') }}</span><input name="longitude" value="{{ old('longitude', $customer->longitude ?? '') }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label>
    <label class="block"><span class="text-sm text-slate-300">{{ __('Geofence radius (m)') }}</span><input type="number" min="25" max="1000" name="geofence_radius_meters" value="{{ old('geofence_radius_meters', $customer->geofence_radius_meters ?? 100) }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3" required></label>
    <label class="flex items-center gap-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $customer->is_active ?? true))><span>{{ __('Active customer') }}</span></label>
</div>
