<x-layouts.app>
@php $limit = $customer->credit_limit === null ? null : (float) $customer->credit_limit; $outstanding = (float) $creditSnapshot['outstanding_balance']; $utilization = $limit !== null && $limit > 0 ? min(999, round(($outstanding / $limit) * 100)) : null; @endphp
<div class="mb-6 flex items-start justify-between gap-4"><div><h1 class="text-2xl font-bold">{{ $customer->name }}</h1><p class="mt-1 text-sm text-slate-400">{{ $customer->code }} · {{ $customer->territory?->name ?? __('No territory') }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('admin.customers.statement', $customer) }}" class="rounded-xl bg-white/10 px-4 py-2.5 font-semibold">{{ __('Statement') }}</a>@if(auth()->user()->hasPermission('customers:manage'))<a href="{{ route('admin.customers.edit', $customer) }}" class="rounded-xl bg-indigo-500 px-4 py-2.5 font-semibold">{{ __('Edit') }}</a>@endif</div></div>
<div class="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
<div class="rounded-2xl border border-white/10 bg-slate-900 p-5"><p class="text-xs uppercase tracking-wide text-slate-400">{{ __('Outstanding') }}</p><p class="mt-2 text-2xl font-bold">{{ $creditSnapshot['currency'] }} {{ number_format($outstanding, 2) }}</p></div>
<div class="rounded-2xl border border-white/10 bg-slate-900 p-5"><p class="text-xs uppercase tracking-wide text-slate-400">{{ __('Credit limit') }}</p><p class="mt-2 text-2xl font-bold">{{ $limit === null ? __('No limit') : $customer->credit_currency.' '.number_format($limit, 2) }}</p></div>
<div class="rounded-2xl border border-white/10 bg-slate-900 p-5"><p class="text-xs uppercase tracking-wide text-slate-400">{{ __('Credit terms') }}</p><p class="mt-2 text-2xl font-bold">{{ $customer->credit_terms_days }} {{ __('days') }}</p></div>
<div class="rounded-2xl border border-white/10 bg-slate-900 p-5"><p class="text-xs uppercase tracking-wide text-slate-400">{{ __('Credit utilization') }}</p><p class="mt-2 text-2xl font-bold">{{ $utilization === null ? '—' : $utilization.'%' }}</p></div>
</div>
<div class="grid gap-5 lg:grid-cols-2">
<section class="rounded-2xl border border-white/10 bg-slate-900 p-5"><dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-slate-400">{{ __('Contact') }}</dt><dd>{{ $customer->contact_person ?? '—' }}</dd></div><div><dt class="text-sm text-slate-400">{{ __('Phone') }}</dt><dd>{{ $customer->phone ?? '—' }}</dd></div><div><dt class="text-sm text-slate-400">{{ __('Coordinates') }}</dt><dd>{{ $customer->latitude ?? '—' }}, {{ $customer->longitude ?? '—' }}</dd></div><div><dt class="text-sm text-slate-400">{{ __('Geofence') }}</dt><dd>{{ $customer->geofence_radius_meters }} m</dd></div><div><dt class="text-sm text-slate-400">{{ __('Price list') }}</dt><dd>{{ $customer->priceList?->name ?? __('Base prices') }}</dd></div><div class="sm:col-span-2"><dt class="text-sm text-slate-400">{{ __('Address') }}</dt><dd>{{ $customer->address ?? '—' }}</dd></div></dl></section>
<section class="rounded-2xl border border-white/10 bg-slate-900 p-5"><h2 class="font-semibold">{{ __('Receivables aging') }}</h2><div class="mt-4 space-y-4">@forelse($aging as $row)<div class="rounded-xl bg-slate-950 p-4"><div class="mb-3 flex items-center justify-between"><span class="font-semibold">{{ $row['currency'] }}</span><span>{{ __('Total') }} {{ number_format($row['outstanding_total'], 2) }}</span></div><div class="grid grid-cols-2 gap-3 text-sm sm:grid-cols-5"><div><p class="text-slate-500">{{ __('Current') }}</p><p>{{ number_format($row['current'], 2) }}</p></div><div><p class="text-slate-500">1–30</p><p>{{ number_format($row['days_1_30'], 2) }}</p></div><div><p class="text-slate-500">31–60</p><p>{{ number_format($row['days_31_60'], 2) }}</p></div><div><p class="text-slate-500">61–90</p><p>{{ number_format($row['days_61_90'], 2) }}</p></div><div><p class="text-slate-500">90+</p><p class="{{ $row['days_90_plus'] > 0 ? 'text-rose-300' : '' }}">{{ number_format($row['days_90_plus'], 2) }}</p></div></div></div>@empty<p class="text-sm text-slate-400">{{ __('No credit receivables.') }}</p>@endforelse</div></section>
<section class="rounded-2xl border border-white/10 bg-slate-900 p-5"><h2 class="font-semibold">{{ __('Route memberships') }}</h2><div class="mt-4 space-y-2">@forelse($customer->routeMemberships as $membership)<a href="{{ route('admin.routes.show', $membership->route) }}" class="block rounded-xl bg-slate-950 p-3">{{ $membership->route?->name }} · {{ __('stop') }} {{ $membership->sequence_number }}</a>@empty<p class="text-sm text-slate-400">{{ __('Not assigned to a route.') }}</p>@endforelse</div></section>
<section class="rounded-2xl border border-white/10 bg-slate-900 p-5"><div class="flex items-center justify-between gap-3"><h2 class="font-semibold">{{ __('Follow-ups') }}</h2><a href="{{ route('admin.follow-ups.index') }}" class="text-sm text-indigo-300 hover:underline">{{ __('All follow-ups') }}</a></div><div class="mt-4 space-y-3">@forelse($customer->followUps->take(8) as $followUp)<div class="rounded-xl bg-slate-950 p-3"><div class="flex justify-between gap-3"><span class="font-medium">{{ __(str($followUp->type)->title()->toString()) }}</span><span class="text-xs {{ $followUp->status === 'pending' && $followUp->due_at?->isPast() ? 'text-rose-300' : 'text-slate-400' }}">{{ $followUp->due_at?->copy()->setTimezone($timezone)->format('Y-m-d H:i') }}</span></div><div class="mt-1 text-xs text-slate-400">{{ $followUp->assignedSalesman?->full_name ?? __('Unassigned') }} · {{ __(str($followUp->status)->title()->toString()) }}</div>@if($followUp->notes)<p class="mt-2 text-sm">{{ $followUp->notes }}</p>@endif</div>@empty<p class="text-sm text-slate-400">{{ __('No follow-ups scheduled.') }}</p>@endforelse</div>
@if(auth()->user()->hasPermission('customers:manage'))<form method="POST" action="{{ route('admin.customers.follow-ups.store', $customer) }}" class="mt-5 grid gap-3 border-t border-white/10 pt-5 sm:grid-cols-2">@csrf<select name="type" class="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5">@foreach(\App\Models\CustomerFollowUp::TYPES as $type)<option value="{{ $type }}">{{ __(str($type)->title()->toString()) }}</option>@endforeach</select><select name="priority" class="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5">@foreach(\App\Models\CustomerFollowUp::PRIORITIES as $priority)<option value="{{ $priority }}" @selected($priority === 'normal')>{{ __(str($priority)->title()->toString()) }}</option>@endforeach</select><select name="assigned_salesman_id" class="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5"><option value="">{{ __('Unassigned') }}</option>@foreach($salesmen as $salesman)<option value="{{ $salesman->id }}">{{ $salesman->employee_code }} · {{ $salesman->full_name }}</option>@endforeach</select><input type="datetime-local" name="due_at" value="{{ $defaultFollowUpAt }}" class="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5" required><textarea name="notes" rows="2" placeholder="{{ __('Follow-up notes') }}" class="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 sm:col-span-2"></textarea><button class="rounded-xl bg-indigo-500 px-4 py-2.5 font-semibold sm:col-span-2">{{ __('Schedule follow-up') }}</button></form>@endif
</section>
<section class="rounded-2xl border border-white/10 bg-slate-900 p-5 lg:col-span-2"><div class="flex items-center justify-between gap-3"><h2 class="font-semibold">{{ __('Recent call activity') }}</h2><a href="{{ route('admin.call-activities.index') }}" class="text-sm text-indigo-300 hover:underline">{{ __('All calls') }}</a></div><div class="mt-4 overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="text-slate-400"><tr><th class="pb-2 pr-4">{{ __('Called') }}</th><th class="pb-2 pr-4">{{ __('Salesman') }}</th><th class="pb-2 pr-4">{{ __('Outcome') }}</th><th class="pb-2">{{ __('Notes') }}</th></tr></thead><tbody class="divide-y divide-white/10">@forelse($customer->callActivities->take(20) as $call)<tr><td class="py-3 pr-4">{{ $call->called_at?->format('Y-m-d H:i') }}</td><td class="py-3 pr-4">{{ $call->user?->name ?? '—' }}</td><td class="py-3 pr-4">{{ $call->outcome ? str($call->outcome)->replace('_', ' ')->title() : __('Not recorded') }}</td><td class="py-3">{{ $call->notes ?? '—' }}</td></tr>@empty<tr><td colspan="4" class="py-5 text-slate-400">{{ __('No call activity recorded.') }}</td></tr>@endforelse</tbody></table></div></section>
</div>
</x-layouts.app>
