<x-layouts.app>
<div class="mb-6 flex flex-wrap items-start justify-between gap-4">
    <div><a href="{{ route('admin.leads.index') }}" class="text-xs font-semibold text-indigo-300 hover:text-indigo-200">← {{ __('Leads & sales pipeline') }}</a><h1 class="mt-2 text-2xl font-bold tracking-tight">{{ $lead->name }}</h1><div class="mt-2 flex flex-wrap gap-2 text-xs"><span class="rounded-full bg-indigo-500/10 px-2.5 py-1 text-indigo-300">{{ __(str($lead->stage)->replace('_', ' ')->title()->toString()) }}</span><span class="rounded-full bg-white/5 px-2.5 py-1 text-slate-400">{{ __($lead->priority) }}</span><span class="rounded-full bg-white/5 px-2.5 py-1 text-slate-400">{{ $lead->probability }}%</span></div></div>
    @if($lead->convertedCustomer)<a href="{{ route('admin.customers.show', $lead->convertedCustomer) }}" class="rounded-xl bg-emerald-500/10 px-4 py-2.5 text-sm font-semibold text-emerald-300">{{ __('Open converted customer') }}</a>@endif
</div>

<div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
    <section class="space-y-5">
        <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <div class="rounded-2xl border border-white/10 bg-slate-900 p-4"><p class="text-xs text-slate-500">{{ __('Estimated value') }}</p><p class="mt-2 font-semibold">{{ $lead->estimated_value !== null ? $lead->currency.' '.number_format((float) $lead->estimated_value, 2) : '—' }}</p></div>
            <div class="rounded-2xl border border-white/10 bg-slate-900 p-4"><p class="text-xs text-slate-500">{{ __('Owner') }}</p><p class="mt-2 font-semibold">{{ $lead->assignedSalesman?->full_name ?? __('Unassigned') }}</p></div>
            <div class="rounded-2xl border border-white/10 bg-slate-900 p-4"><p class="text-xs text-slate-500">{{ __('Expected close') }}</p><p class="mt-2 font-semibold">{{ $lead->expected_close_date?->format('M j, Y') ?? '—' }}</p></div>
            <div class="rounded-2xl border border-white/10 bg-slate-900 p-4"><p class="text-xs text-slate-500">{{ __('Source') }}</p><p class="mt-2 font-semibold">{{ __(str($lead->source)->replace('_', ' ')->title()->toString()) }}</p></div>
        </div>

        <div class="rounded-2xl border border-white/10 bg-slate-900 p-5"><h2 class="font-semibold">{{ __('Prospect details') }}</h2><div class="mt-4 grid gap-4 text-sm md:grid-cols-2"><div><p class="text-xs text-slate-500">{{ __('Contact person') }}</p><p class="mt-1">{{ $lead->contact_person ?: '—' }}</p></div><div><p class="text-xs text-slate-500">{{ __('Phone') }}</p><p class="mt-1">{{ $lead->phone ?: '—' }}</p></div><div><p class="text-xs text-slate-500">{{ __('Email') }}</p><p class="mt-1">{{ $lead->email ?: '—' }}</p></div><div><p class="text-xs text-slate-500">{{ __('Territory') }}</p><p class="mt-1">{{ $lead->territory?->name ?? '—' }}</p></div></div>@if($lead->address)<p class="mt-4 text-sm text-slate-400">{{ $lead->address }}</p>@endif @if($lead->notes)<p class="mt-4 whitespace-pre-line text-sm leading-6 text-slate-300">{{ $lead->notes }}</p>@endif @if($lead->lost_reason)<div class="mt-4 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-200">{{ __('Lost reason') }}: {{ $lead->lost_reason }}</div>@endif</div>

        <section class="rounded-2xl border border-white/10 bg-slate-900"><div class="border-b border-white/10 px-5 py-4"><h2 class="font-semibold">{{ __('Activity timeline') }}</h2><p class="mt-1 text-xs text-slate-500">{{ __('Calls, meetings, notes, stage changes, assignments and conversion history.') }}</p></div><div class="divide-y divide-white/10">@forelse($lead->activities as $activity)<article class="px-5 py-4"><div class="flex items-start justify-between gap-3"><div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-white/5 px-2 py-1 text-[10px] uppercase text-slate-400">{{ __(str($activity->type)->replace('_', ' ')->title()->toString()) }}</span><span class="text-xs text-slate-600">{{ $activity->user?->name ?? __('System') }}</span></div>@if($activity->notes)<p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-300">{{ $activity->notes }}</p>@endif</div><time class="shrink-0 text-[10px] text-slate-600">{{ $activity->occurred_at?->format('M j H:i') }}</time></div></article>@empty<div class="px-5 py-10 text-center text-sm text-slate-500">{{ __('No activity yet.') }}</div>@endforelse</div></section>
    </section>

    @if($canManage)
    <aside class="space-y-4 self-start xl:sticky xl:top-6">
        <form method="POST" action="{{ route('admin.leads.update', $lead) }}" class="space-y-3 rounded-2xl border border-white/10 bg-slate-900 p-5">@csrf @method('PUT')<h2 class="font-semibold">{{ __('Update opportunity') }}</h2><select name="stage" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5">@foreach($stages as $stage)<option value="{{ $stage }}" @selected($lead->stage === $stage)>{{ __(str($stage)->replace('_', ' ')->title()->toString()) }}</option>@endforeach</select><select name="priority" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5">@foreach($priorities as $priority)<option value="{{ $priority }}" @selected($lead->priority === $priority)>{{ __(str($priority)->title()->toString()) }}</option>@endforeach</select><select name="assigned_salesman_id" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5"><option value="">{{ __('Unassigned') }}</option>@foreach($salesmen as $salesman)<option value="{{ $salesman->id }}" @selected((int) $lead->assigned_salesman_id === (int) $salesman->id)>{{ $salesman->employee_code }} · {{ $salesman->full_name }}</option>@endforeach</select><select name="territory_id" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5"><option value="">{{ __('No territory') }}</option>@foreach($territories as $territory)<option value="{{ $territory->id }}" @selected((int) $lead->territory_id === (int) $territory->id)>{{ $territory->code }} · {{ $territory->name }}</option>@endforeach</select><div class="grid grid-cols-[1fr_90px] gap-2"><input type="number" min="0" step="0.01" name="estimated_value" value="{{ $lead->estimated_value }}" class="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5"><input name="currency" value="{{ $lead->currency }}" maxlength="3" class="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 uppercase"></div><input type="date" name="expected_close_date" value="{{ $lead->expected_close_date?->toDateString() }}" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5"><textarea name="lost_reason" rows="2" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5" placeholder="{{ __('Lost reason (required context when lost)') }}">{{ $lead->lost_reason }}</textarea><textarea name="notes" rows="3" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5" placeholder="{{ __('Opportunity notes') }}">{{ $lead->notes }}</textarea><button class="w-full rounded-xl bg-indigo-500 px-4 py-2.5 font-semibold hover:bg-indigo-400">{{ __('Save changes') }}</button></form>

        <form method="POST" action="{{ route('admin.leads.activities.store', $lead) }}" class="space-y-3 rounded-2xl border border-white/10 bg-slate-900 p-5">@csrf<h2 class="font-semibold">{{ __('Add activity') }}</h2><select name="type" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5">@foreach($activityTypes as $type)<option value="{{ $type }}">{{ __(str($type)->replace('_', ' ')->title()->toString()) }}</option>@endforeach</select><textarea name="notes" required rows="4" maxlength="5000" class="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5" placeholder="{{ __('What happened?') }}"></textarea><button class="w-full rounded-xl bg-white/10 px-4 py-2.5 font-semibold hover:bg-white/20">{{ __('Add to timeline') }}</button></form>

        @if(!$lead->converted_customer_id)
        <form method="POST" action="{{ route('admin.leads.convert', $lead) }}" class="rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-5">@csrf<h2 class="font-semibold text-emerald-200">{{ __('Convert to customer') }}</h2><p class="mt-2 text-xs leading-5 text-emerald-100/70">{{ __('Marks the opportunity Won and creates a customer. If the same phone or email already exists, FieldPulse links that customer instead of creating a duplicate.') }}</p><button class="mt-4 w-full rounded-xl bg-emerald-500 px-4 py-2.5 font-semibold text-slate-950 hover:bg-emerald-400">{{ __('Convert lead') }}</button></form>
        @endif
    </aside>
    @endif
</div>
</x-layouts.app>
