<x-layouts.app>
<div class="mb-6"><h1 class="text-2xl font-bold">{{ __('Follow-ups') }}</h1><p class="mt-1 text-sm text-slate-400">{{ __('Planned customer actions, payment reminders, calls and visits.') }}</p></div>
<form method="GET" class="mb-5 flex flex-wrap gap-3"><select name="status" class="rounded-xl border border-white/10 bg-slate-900 px-4 py-3">@foreach(\App\Models\CustomerFollowUp::STATUSES as $value)<option value="{{ $value }}" @selected($filters['status'] === $value)>{{ __(str($value)->title()->toString()) }}</option>@endforeach</select><select name="salesman" class="rounded-xl border border-white/10 bg-slate-900 px-4 py-3"><option value="">{{ __('All salesmen') }}</option>@foreach($salesmen as $salesman)<option value="{{ $salesman->uuid }}" @selected($filters['salesman'] === $salesman->uuid)>{{ $salesman->employee_code }} · {{ $salesman->full_name }}</option>@endforeach</select><button class="rounded-xl bg-indigo-500 px-4 py-3 font-semibold">{{ __('Filter') }}</button></form>
<div class="overflow-hidden rounded-2xl border border-white/10 bg-slate-900"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-white/5"><tr><th class="px-5 py-3">{{ __('Due') }}</th><th class="px-5 py-3">{{ __('Customer') }}</th><th class="px-5 py-3">{{ __('Assigned salesman') }}</th><th class="px-5 py-3">{{ __('Type') }}</th><th class="px-5 py-3">{{ __('Priority') }}</th><th class="px-5 py-3">{{ __('Notes') }}</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-white/10">
@forelse($followUps as $followUp) @php $dueLocal=$followUp->due_at?->copy()->setTimezone($timezone); $overdue=$followUp->status==='pending' && $followUp->due_at?->isPast(); @endphp
<tr><td class="px-5 py-4"><div class="{{ $overdue ? 'font-semibold text-rose-300' : '' }}">{{ $dueLocal?->format('Y-m-d H:i') }}</div>@if($overdue)<div class="text-xs text-rose-400">{{ __('Overdue') }}</div>@endif</td><td class="px-5 py-4"><a href="{{ route('admin.customers.show', $followUp->customer) }}" class="hover:text-indigo-300">{{ $followUp->customer?->name }}</a></td><td class="px-5 py-4">{{ $followUp->assignedSalesman?->full_name ?? __('Unassigned') }}</td><td class="px-5 py-4">{{ __(str($followUp->type)->title()->toString()) }}</td><td class="px-5 py-4">{{ __(str($followUp->priority)->title()->toString()) }}</td><td class="max-w-sm px-5 py-4">{{ $followUp->notes ?? '—' }}</td><td class="px-5 py-4">@if($followUp->status === 'pending' && auth()->user()->hasPermission('customers:manage'))<form method="POST" action="{{ route('admin.follow-ups.status', $followUp) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="completed"><button class="rounded-lg bg-emerald-500/15 px-3 py-2 text-xs font-semibold text-emerald-300">{{ __('Complete') }}</button></form>@else<span class="text-slate-400">{{ __(str($followUp->status)->title()->toString()) }}</span>@endif</td></tr>
@empty<tr><td colspan="7" class="px-5 py-10 text-center text-slate-400">{{ __('No follow-ups found.') }}</td></tr>@endforelse
</tbody></table></div></div><div class="mt-5">{{ $followUps->links() }}</div>
</x-layouts.app>
