<x-layouts.app title="Gamification bonuses">
<div class="space-y-6">
 <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-wider text-indigo-300">Gamification</p><h1 class="mt-1 text-2xl font-bold">Bonus approvals</h1><p class="mt-2 text-sm text-slate-400">Review earned target bonuses, approve them, then mark them paid. Every transition is audited.</p></div><a href="{{ route('admin.gamification.index') }}" class="fp-btn fp-btn-secondary">Back to Gamification</a></div>
 <form class="flex gap-3"><select name="status" class="fp-input"><option value="">All statuses</option>@foreach(['earned','approved','paid'] as $s)<option value="{{ $s }}" @selected($status===$s)>{{ ucfirst($s) }}</option>@endforeach</select><button class="fp-btn fp-btn-secondary">Filter</button></form>
 <div class="overflow-hidden rounded-2xl border border-white/10 bg-slate-900/60"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-white/10 text-sm"><thead class="bg-white/5 text-left text-xs uppercase text-slate-400"><tr><th class="px-5 py-3">Salesman</th><th class="px-5 py-3">Target</th><th class="px-5 py-3">Milestone</th><th class="px-5 py-3">Bonus</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Earned</th><th class="px-5 py-3">Action</th></tr></thead>
 <tbody class="divide-y divide-white/5">@forelse($bonuses as $bonus)<tr><td class="px-5 py-4 font-medium">{{ $bonus->salesman?->full_name }}</td><td class="px-5 py-4">{{ str($bonus->target?->target_type)->replace('_',' ')->title()->toString() }}</td><td class="px-5 py-4">{{ $bonus->milestone_percent }}%</td><td class="px-5 py-4 font-semibold">{{ number_format((float)$bonus->amount,2) }} {{ $bonus->currency }}</td><td class="px-5 py-4">{{ ucfirst($bonus->status) }}</td><td class="px-5 py-4">{{ $bonus->earned_at?->format('Y-m-d H:i') }}</td><td class="px-5 py-4">@if($bonus->status!=='paid')<form method="POST" action="{{ route('admin.gamification.bonuses.update',$bonus) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $bonus->status==='earned'?'approved':'paid' }}"><button class="fp-btn fp-btn-primary">{{ $bonus->status==='earned'?'Approve':'Mark paid' }}</button></form>@else<span class="text-emerald-300">Completed</span>@endif</td></tr>@empty<tr><td colspan="7" class="px-5 py-10 text-center text-slate-500">No gamification bonuses found.</td></tr>@endforelse</tbody></table></div></div>
 {{ $bonuses->links() }}
</div>
</x-layouts.app>
